### ISSUE TITLE
No audio output from 1.0.7 M10

### ISSUE THREAD

**Issue by jonawebb** [Red5/red5-service#4]
I'm investigating whether 1.0.7 M10 addresses an audio issue (RTMP decode failure) I encountered in release 1.0.5 with an iOS app that connects to my Red5 servlet. I managed to get my servlet running under 1.0.7 M10. It connects fine, and audio from my app to the server is transmitted without problems, but I get no audio output to my app. The same thing happens with my Flash app running under Chrome. Both the iOS and Chrome apps subscribe to a ClientBroadcastStream for their output.
I don't see any failures in the logs -- but there are a lot of messages:
[WARN] [NioProcessor-3] org.apache.mina.core.service.IoProcessor - Create a new selector. Selected is 0, delta = 0
This happens over and over.
I haven't been able to track down exactly where the audio to my app is getting lost -- it appears that it is received by my servlet and passed to ClientBroadcastStream, at least.

**Comment by mondain** [comment]
You're seeing some sort of socket issue in Mina, that's not an error in Red5 as technically it hasn't made it that far yet. Flash and HLS audio most certainly work in M10 as its been thoroughly tested in Red5 Pro 1.0.

**Comment by jonawebb** [comment]
I was previously using 1.0.5, so it makes sense that the 1.0 Pro release works. I'm just having a problem with 1.0.7 M10. Audio to the server comes through fine; I'm just not getting any audio at all from the server to the client. And I'm sure the audio gets to the server--I can trace the AudioData packets that far.

**Comment by jonawebb** [comment]
I found the source of the problem. It was that the type of the object passed with a CreateStream call is sometimes Double, while in 1.0.5 it was always Integer. (WTF, BTW. High precision stream ids?)
Anyway, this played havoc with my code, which interacts with Red5 in a non-standard way. Probably seemed like a good idea at the time. There is no problem with Red5 itself.

**Comment by mondain** [comment]
AMF0 doesnt have an Integer type and thus on the java side that makes their Number a number in java which is extended by Double and Integer. Red5 in its latest versions has been set to use strict AMF0 handling of input. We switched everything from "int" to Number in Red5 for stream ids; it keeps us compatible with AMS and removes several hacks that were being done on the number handling.
